pod 'Mantle', '~> 2.0.7'
pod 'AFNetworking', '~> 3.1.0'
pod 'Masonry', '0.6.0'
pod 'RPJSONValidator', '~> 0.2.0'
pod 'RegexKitLite', '~> 4.0'
pod 'SDWebImage', '~> 3.7.2'
pod 'libextobjc', '~> 0.4.1'
pod 'MJRefresh'
